spring.application.name=demo

spring.mongodb.uri=mongodb://localhost:27017/postdb

server.port=8080

# ==============================
# LOGGING CONFIGURATION
# ==============================

logging.level.root=INFO
logging.level.com.example.demo=INFO

# Show Correlation ID in console logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n